swagger: '2.0'
info:
  description: Data Metrics API
  version: "1.0.0.2"
  title: Data Metrics API
  contact:
    name: Data Metrics API Support
    email: support@makedatacount.org
    url: https://makedatacount.org
    # Authors: 
    #    Stephen Abrams, California Digital Library
    #    Amber Budden, NCEAS, DataONE
    #    John Chodacki, California Digital Library
    #    Trisha Cruse, DataCite
    #    Martin Fenner, DataCite
    #    Kristian Garza, DataCite
    #    Christopher Jones, NCEAS, DataONE
    #    Matthew Jones, NCEAS, DataONE
    #    Daniella Lowenberg, California Digital Library
    #    Rushiraj Nenuji, NCEAS 
    #    Dave Vieglais, DataONE
    #    Lauren Walker, NCEAS, DataONE


  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


# Tags used for organizing operations
tags:
- name: admins
  description: Operations available to authenticated administrators
- name: public
  description: Operations available to the public
- name: authenticatedUser
  description: Operations available to an authenticated user


# REST API endpoints
paths:
  /events:
    post:
      tags:
        - authenticatedUser
      summary: Add event items
      operationId: addEvent
      description: Add event items to the events collection
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: session
        description: 'Authentication session (JWT token).'
        type: string
        required: true
      - in: body
        name: events
        description: Events item to add
        required: true
        schema:
          $ref: '#/definitions/Events'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists


  /metrics/{id}:
    get:
      tags:
      - public
      summary: Get metrics by resource identifier
      operationId: getMetrics
      description: |
        Returns a Metrics object with summarized and detailed metrics 
        for a resource with a given identifier
      produces:
      - application/json
      parameters:
      - in: header
        name: session
        description: 'Authentication session (JWT token).'
        type: string
      - in: path
        name: id
        description: The identifier of the resource to be described by the returned metrics
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Metrics'
        400:
          description: bad input parameter
  
  
  /metrics/metricssummaries/{id}:
    get:
      tags:
      - public
      summary: Get metrics summaries by resource identifier
      operationId: getMetricsSummaries
      description: |
        Returns a metrics summary object with summarized metrics for a resource with a given identifier
      produces:
      - application/json
      parameters:
      - in: header
        name: session
        description: 'Authentication session (JWT token).'
        type: string
      - in: path
        name: id
        description: The identifier of the resource to be described by the returned metrics
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/MetricSummary'
        400:
          description: bad input parameter


# Model Type Definitions
definitions:

  DateTime:
    type: string
    description:
      'The date of the event expressed in ISO 8601 format YYYY-mm-DDTHH:MM:SS.SSS+0000'


  MetricByTimeAndLocation:
    type: object
    required:
      - time
      - location
      - value
    properties:
      time:
        type: string
        description: The time period representing the event count
        example: '2018-01'
      location: 
        type: string
        description: The ISO administrative area code at the country or state / province level
        example: 'US'
      value:
        type: number
        format: int32
        description: The value of the metric at the given time and location.
        example: 5948


  # A citation event of an object with minimum citable metadata
  Citation:
    required:
      - eventId
      - date
      - cites
      - identifier
      - authors
      - title
      - publicationDate
      - publisher
    properties:
      cites:
        type: string
        description: The identifier of the object being cited
        example: 'doi:10.67890/HIJKLM'
      identifier:
        type: string
        description: The identifier of the work citing the object
        example: 'doi:10.12345/ABCDEFG'
      authors:
        type: array
        items:
          type: string
      title:
        type: string
        description: The title of the work citing the object
        example: ''
      publicationDate:
        $ref: '#/definitions/DateTime'
      publisher:
        type: string
        description: The publisher of the work citing the object
      url:
        type: string
        description: The canonical url of the work citing the object
        example: 'https://doi.org/doi:10.12345/ABCDEFG'
      eventId:
        type: string
        description: 'The potentially unique event identifier'
        example: 'f0b0a80c-2c1d-4a3c-b233-7372967758e3'
      date:
        $ref: '#/definitions/DateTime'
      eventType:
        type: string
        description: 'The type of event : Citation'


  # An investigation event (view) of an object      
  Investigation:
    required:
      - identifier
      - eventId
      - date
    properties:
      identifier:
        type: string
        description: The identifier of the investigated object
        example: 'doi:10.12345/ABCDEFG'
      eventId:
        type: string
        description: 'The potentially unique event identifier'
        example: 'f0b0a80c-2c1d-4a3c-b233-7372967758e3'
      date:
        $ref: '#/definitions/DateTime'
      eventType:
        type: string
        description: 'The type of event : Investigation'


  # A request (download) event of an object
  Request:
    required:
      - identifier
      - eventId
      - date
    properties:
      identifier:
        type: string
        description: The identifier of the requested object
        example: 'doi:10.12345/ABCDEFG'
      eventId:
        type: string
        description: 'The potentially unique event identifier'
        example: 'f0b0a80c-2c1d-4a3c-b233-7372967758e3'
      date:
        $ref: '#/definitions/DateTime'
      eventType:
        type: string
        description: 'The type of event : Request'


  # A change (update) event of an object with change type metadata
  Change:
    required:
      - identifier
      - eventId
      - date
    properties:
      identifier:
        type: string
        description: The identifier of the changed object
        example: 'doi:10.12345/ABCDEFG'
      obsoletedBy: 
        type: string
      eventId:
        type: string
        description: 'The potentially unique event identifier'
        example: 'f0b0a80c-2c1d-4a3c-b233-7372967758e3'
      date:
        $ref: '#/definitions/DateTime'
      eventType:
        type: string
        description: 'The type of event : Change'


  # An annotation (assertion) event of an object
  Annotation:
    required:
      - identifier
      - eventId
      - date
    properties:
      identifier:
        type: string
      eventId:
        type: string
        description: 'The potentially unique event identifier'
        example: 'f0b0a80c-2c1d-4a3c-b233-7372967758e3'
      date:
        $ref: '#/definitions/DateTime'
      eventType:
        type: string
        description: 'The type of event : Annotation'


  #A collection of Events Object
  Events:
    type: array
    items:
      $ref: '#/definitions/Citation'
    properties:
      maxitems:
        type: integer
        description: 'Maximum length of the Events Collection.'
        example: '1000'


  # A collection of metrics objects
  Metrics:
    type: array
    items: 
      $ref: '#/definitions/Metric'
      

  # A citation metric object
  Metric:
    required:
      - identifier
    properties:
      totalCount:
        type: integer
        format: int32
      date:
        $ref: '#/definitions/DateTime'
      metricsByTimeAndLocation:
        type: array
        items:
          $ref: '#/definitions/MetricByTimeAndLocation'
      identifier:
          type: string
          description: 
            'An identifier representing the described resource'
          example: 'doi:10.12345/ABCDEFG'
      metricType:
        type: string
        description: 
          'The type of metric (citation, investigation, request, volume, funding org, award number), including counts of citation, investigation, requests and bytes of volume transfered'
        example: 'citation'


  MetricSummary:
    required:
      - metricType
    properties:
      metricType:
        type: string
        description: ''
        example: 'citation / investigation / requests / volume'
      metricCategory:
        type: string
        description: ''
        example: 'funding / organization / award number'
      totalCountTypeByCategory:
        type: number
        example: '123'
      typeByCategory:
        type: array
        items:
          $ref:  '#/definitions/MetricByTimeAndLocation'


# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /NCEAS/data-metrics/1.0.0.2
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /nenuji/data-metrics/1.0.0.2